### ISSUE TITLE
Проект Stories

### ISSUE THREAD

**Issue by lulldev** [gstaizer/Stories#1]
- [x] вынести в корень проекта содержимое папки lw5

**Comment by lulldev** [comment]
- [ ] сборщик фронтенда не содержит сборки build. Так же нет минификации файлов.

**Comment by lulldev** [comment]
- [ ] добавить переключение по сторис в рамках одного профиля

**Comment by lulldev** [comment]
- [ ] добавить возможность просмотра сторис разных профилей

**Comment by lulldev** [comment]
- [ ] добавить переключение на след. стори по клику

**Comment by lulldev** [comment]
- [ ] улучшить работу со сторис с точки зрения программного функционала.
StoriesBlock -  содержит массив Stories. в массиве - объекты new Stories().
StoriesBlock::show() - проходи по массиву и у каждой stories.show()

**Comment by gstaizer** [comment]
Предложение такое:
[ ] - реализовать api метод на стороне сервера для получения необходимых данных
[ ] - при просмотре историй - учитывать какие истории просмотрены и при повторном открытии - показывать уже следующую историю или профиль. (аналог инсты). учет просмотренных историй - можно вести в local-storage или отправлять на API.

**Comment by gstaizer** [comment]
[  ] -

**Comment by gstaizer** [comment]
- [ ] реализовать api метод на стороне сервера для получения необходимых данных
- [ ] при просмотре историй - учитывать какие истории просмотрены и при повторном открытии - показывать уже следующую историю или профиль. (аналог инсты). учет просмотренных историй - можно вести в local-storage или отправлять на API.

**Comment by gstaizer** [comment]
я помню, что шла речь о выставлении приоритета у каждого файла, но не понял зачем эта функция, если порядок воспроизведения можно так же спокойно менять, меняя их порядок в db.json
